version: '3'
services:
  aura:
    container_name: aura
    image: ibcbridgedemo:aura
    volumes:
      - ./config/aura:/home/aura/.aura
    ports:
      - "26657:26657"
      - "1317:1317"
      - "9090:9090"
  juno:
    container_name: juno
    image: ibcbridgedemo:juno
    volumes:
      - ./config/juno:/home/juno/.juno
    ports:
      - "26655:26657"
      - "1315:1317"
      - "9088:9090"
  relayer-aura-juno:
    container_name: relayer
    image: ibcbridgedemo:relayer
    volumes:
      - ./config/relayer-config:/home/relayer/.relayer
    restart: always
    command: [ "bash", "start.sh", "aura-juno" ]
